### PR TITLE
Add smoke test action

### PR DESCRIPTION
**Pull request by jaapio**

### CODE REVIEW

**Comment by jaapio** [comment]
@theseer This is a first setup, but somehow it fails on a different error now. 
I will continue on this later. If you have a suggestion how the error can be fixed, I would love to hear it :-D

**Comment by theseer** [comment]
> @theseer This is a first setup, but somehow it fails on a different error now.
> I will continue on this later. If you have a suggestion how the error can be fixed, I would love to hear it :-D

If you're talking about the 403 Error, that means probably we somehow ran over the github API quota. Kind of ironic that Github is blocking itself, as it seems.

Phive can make use of an auth token for that but I don't know how to configure the github action for something like that? I for rather obvious reasons cannot store it in the phive configuration ;)


I can't say anything about the other "cancled" type errors...

**Comment by jaapio** [comment]
Is there an environment variable that we can set to authenticate on the github api?

**Comment by theseer** [comment]
> Is there an environment variable that we can set to authenticate on the github api?

Sure. GITHUB_AUTH_TOKEN.

**Comment by jaapio** [comment]
I tried multiple stategies to reproduce the issue, currently the setup is almost equal to what we have in phpdocumentor except for the cache we are using.... But since we get an error during the download of the gpg key I don't expect this to be the problem. I don't know what is wrong.

I will continue the debugging on phpDocumentor to see what is going on.

**Comment by theseer** [comment]
Thanks so much already! Having a smoke test build matrix is worth a lot either way :)

**Comment by theseer** [comment]
> I will continue the debugging on phpDocumentor to see what is going on.

@jaapio Do you have a issue number there? Maybe I can help ;-)

**Comment by theseer** [comment]
@jaapio And: Can I merge this already? It looks complete to me...

**Comment by jaapio** [comment]
@theseer You can check the default branch of phpDocumentor for the setup. The output is shown in the actions tab. 
https://github.com/phpDocumentor/phpDocumentor/runs/792765032

Each commit on this branch will trigger a new build. Windows is just always failing with the same error.

About the the merge, I think we need to revert some of commits to use the version of the branch we are running this setup on. Which makes more sense than having an external thing installing phive. I will do that and let you know when I think this is ready.

**Comment by theseer** [comment]
> @theseer You can check the default branch of phpDocumentor for the setup. The output is shown in the actions tab.
> [phpDocumentor/phpDocumentor/runs/792765032](https://github.com/phpDocumentor/phpDocumentor/runs/792765032)
> 
> Each commit on this branch will trigger a new build. Windows is just always failing with the same error.


Given there is no `ext/gnupg` for windows (and thus the setup for it fails in the step before), this setup should fall back to using our shim layer with userland php and an `gnupg` binary exec call.

I wouldn't off hand know why that should fail on this setup but not on the smoke test instances, but there must be something amiss at this very point. If we can add a custom-debug build of phive to those failing instances, we could add some debugging output to that - maybe it helps us to better understand what's going on. 

I presume there is no way to ssh into the instances like on scrutinizer? ;)

> 
> About the the merge, I think we need to revert some of commits to use the version of the branch we are running this setup on. Which makes more sense than having an external thing installing phive. I will do that and let you know when I think this is ready.

Sounds good :)

**Comment by jaapio** [comment]
Ok, this one seems ready for merge. I will extend it later with more scenario's.

**Comment by jaapio** [comment]
> I presume there is no way to ssh into the instances like on scrutinizer? ;

ssh to a windows machine :thinking:, but no... github action does not have a debug mode that I'm aware off.

**Comment by theseer** [comment]
> > I presume there is no way to ssh into the instances like on scrutinizer? ;
> 
> ssh to a windows machine thinking, but no... github action does not have a debug mode that I'm aware off.

Why people still use windows is beyond me... ;-)

But okay, I could create a "debug" branch and create a custom phar from it that we can on the windows instances. It probably will be quite ... verbose.. but that should help. Give me a few minutes ;)

**Pull request merged**
