### PR TITLE
PHPStan Level 5

### PR DESCRIPTION
**Pull request by szepeviktor**
@theseer Here you go! No error up to Level 5

### CODE REVIEW

**Comment by theseer** [comment]
Thanks!

What's the point of the file `test/phpstan-bootstrap.php`?

I have to check/understand the `instanceof` check in the `Factory`, the rest seems fine on first glance.

**Comment by szepeviktor** [comment]
> What's the point of the file `test/phpstan-bootstrap.php`?

We **don't** need HHVM_VERSION, we need class Gnupg to prevent several errors

```
 ------ ------------------------------------------------------------------------------------
  Line   src/Factory.php
 ------ ------------------------------------------------------------------------------------
  322    Return typehint of method PharIo\Phive\Factory::getGnupg() has invalid type Gnupg.
 ------ ------------------------------------------------------------------------------------
```

**Comment by szepeviktor** [comment]
No!

```
 ------ ----------------------------------------
  Line   src/shared/environment/Environment.php
 ------ ----------------------------------------
  95     Constant HHVM_VERSION not found.
 ------ ----------------------------------------
```

**Comment by theseer** [comment]
Okay, I understand why the `test/phpstan-bootstrap.php` file exists, but why is it in `tests`? It's not a test nor is it related to testing.

Maybe we should create a PHPStan folder in `build`?

**Comment by szepeviktor** [comment]
Isn't PHPStan testing?

**Comment by theseer** [comment]
Good question actually but to me it's not. It's static code analysis.

**Comment by szepeviktor** [comment]
In my note I call it zero code coverage testing.
https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/PHP-development.md#ci-outside-tests-mag

**Comment by szepeviktor** [comment]
@theseer Is it okay for you?

**Comment by theseer** [comment]
I'll try to have a look at it tomorrow.

**Comment by theseer** [comment]
I'm not convinced yet we'll keep phpstan around. I'm not a fan of the way errors are suppressed and how the config is build. But we'll see...

**Pull request merged**
