### PR TITLE
Downgrade phpunit for php 7.1 and fix CI

### PR DESCRIPTION
**Pull request by szepeviktor**
@theseer Will it fix CI?

### CODE REVIEW

**Comment by szepeviktor** [comment]
I think it is OK. Only the GitHub API token is missing.

**Comment by szepeviktor** [comment]
@theseer Ci is fixed here. Could you merge?

**Comment by theseer** [comment]
Thanks for the pointers.

I adopted them in a different way though.

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request closed without merging**
