### PR TITLE
Throw exception when target file exists and is not writable

### PR DESCRIPTION
**Pull request by digilist**
If a destination file exists, but is a symlink that points to a non writable file, phive failed with a cryptic error:

```
Linking /home/markus/.phive/phars/phpab-1.25.1.phar to ./tools/phpab
[ERROR]    An error occurred while processing your request:

          symlink(): No such file or directory
          
          #0 src/services/phar/UnixoidPharInstaller.php(17)
          #1 unknown file(0): PharIo\Phive\Cli\Runner->errorHandler()
          #2 src/services/phar/UnixoidPharInstaller.php(17): symlink()
          #3 src/services/phar/PharInstaller.php(37): PharIo\Phive\UnixoidPharInstaller->link()
          #4 src/services/phar/InstallService.php(73): PharIo\Phive\PharInstaller->install()
          #5 src/commands/install/InstallCommand.php(63): PharIo\Phive\InstallService->execute()
          #6 src/commands/install/InstallCommand.php(51): PharIo\Phive\InstallCommand->installRequestedPhar()
          #7 src/shared/cli/Runner.php(211): PharIo\Phive\InstallCommand->execute()
          #8 src/shared/cli/Runner.php(70): PharIo\Phive\Cli\Runner->execute()
          #9 phive(54): PharIo\Phive\Cli\Runner->run()
          #10 {main}

          Environment: PHP 7.3.0
          Phive Version: 0.12.1-2-g868aac1-dirty

          This should not have happened and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!
```

```
# ls -l tools
total 0
lrwxrwxrwx 1 markus markus  8 18. Dez 20:49 phpab -> /foo/bar
```

So it took some debugging to find the actual reason and to fix the issue. This pull requests adds an extra check to throw a better error message.

### CODE REVIEW

**Comment by theseer** [comment]
Thanks for the idea and the PR.

I like the idea but am not fully happy with the implementation: Instead of converting `$destination` to string and use `file_exists`, `is_link` and `is_writeable` the appropriate method(s) should be added to the class `Filename`. Like in that, we'd be consistent to `Directory`.

What do you think?

**Comment by digilist** [comment]
That's a good idea. I updated the code accordingly and opened a new PR for the filesystem component phar-io/filesystem#1

Before merging this, the filesystem changes must be merged and the dependencies updated. That's also the reason why travis is currently failing

**Comment by theseer** [comment]
Will look at it this later. Thanks a lot for the quick response!

**Comment by szepeviktor** [comment]
@theseer Could you take a look at it?

**Comment by theseer** [comment]
Sorry it took so long :)

**Comment by szepeviktor** [comment]
:)

**Pull request merged**
