### PR TITLE
See PHPStan in action

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
@theseer Is it okay for you?

**Comment by szepeviktor** [comment]
@sebastianheuer Could this be merged?

**Comment by szepeviktor** [comment]
Anything left to do here?

**Comment by szepeviktor** [comment]
@theseer phpstan could also check this release :)

**Comment by theseer** [comment]
phpstan is still producing to many false positives.
Like this:

```
theseer@nyda ~/storage/php/phar.io/phive master $ ./tools/phpstan analyse
```

```
Note: Using configuration file /home/theseer/storage/php/phar.io/phive/phpstan.neon.
 188/188 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ ----------------------------------------------------------------------------------------------- 
  Line   src/shared/cli/Runner.php                                                                      
 ------ ----------------------------------------------------------------------------------------------- 
  145    Parameter #1 $error_handler of function set_error_handler expects (callable)|null, array<int,  
         $this(PharIo\Phive\Cli\Runner)|string> given.                                                  
 ------ ----------------------------------------------------------------------------------------------- 

                                                                                                                        
 [ERROR] Found 1 error    
```

Imho, that's b*llsh*t: `array($this, "method")` is a perfectly valid callable.

**Comment by szepeviktor** [comment]
Yes, callables are false positives https://github.com/szepeviktor/phpstan-wordpress/blob/master/example/fix-callable.php
phpstan has way more benefit than false positives.
Please reconsider.

**Comment by theseer** [comment]
There is literally no point in adding a tool to the build process that we know will produce useless results or, if we were to make it passing a requirement, break the build.

I do see the value of phpstan but ony When phpstan is fixed, we can - and probably will - add it.

**Comment by szepeviktor** [comment]
I see.

👋 phpstan 👋

**Pull request closed without merging**
