### PR TITLE
Replace non-ASCII character

### PR DESCRIPTION
**Pull request by szepeviktor**
with its UTF-8 byte triplet

### CODE REVIEW

**Comment by theseer** [comment]
The point of this change being?

**Comment by szepeviktor** [comment]
> The point of this change being?

Being ASCII only.
A benefit of the 90's :)

**Comment by szepeviktor** [comment]
Many tricky problems can be avoided even today!

In CI: `grep -P '[^ -~]'`

**Comment by theseer** [comment]
Well, we do live in 2020 and UTF-8 is a thing.

I don't see why there would be a need to support broken editors that cannot deal with UTF-8 encoded source code.

Sorry, but I prefer to be able to actually *see* the char rather than having to guess. So I won't merge this, but thanks for the effort.

**Comment by szepeviktor** [comment]
Okay-okay.
A lower ASCII only codebase is the Best :)

**Pull request closed without merging**
