### PR TITLE
Fix release diff links

### PR DESCRIPTION
**Pull request by szepeviktor**
@theseer Could you click <kbd>Merge</kbd> here?

### CODE REVIEW

**Comment by theseer** [comment]
I do not understand the intention of this PR.
There is no 0.13.0 release?

**Comment by szepeviktor** [comment]
Excuse me, it **was** in the changelog.

Should I delete it?

**Comment by szepeviktor** [comment]
Shouldn't the link at the bottom be populated? https://github.com/phar-io/phive/commit/a10852fdddc9b69bdf6d937dd6e06680597bca5d#diff-4ac32a78649ca5bdd8e0ba38b7006a1e

**Comment by theseer** [comment]
Right, 0.13. might have been the "expected next release" for a while but so far it didn't make it. We only want to increase the minor number if we actually find the time to add features :)

**Comment by theseer** [comment]
But yes, we probably should update the footer links for the 0.12.3 and 0.12.4 releases. I somehow keep forgetting the footer because I hardly ever scroll down...

**Comment by szepeviktor** [comment]
Finally done. Some trailing spaces disappeared :)

Please do squash my commits.

**Pull request merged**
