### PR TITLE
setup first github action steps

### PR DESCRIPTION
**Pull request by jaapio**
I added a new Github action in `./github/actions/phive-ant` which contains all packages required to run the `ant` setup in this project. This allowed me to define ant tasks that you are familiar with to execute the actions. 

A number of things could be improved:

- One problem I'm currently facing it the installation of tools by phive. The tools are symlinked in a docker container for that specific action. So after the action step is finished the tools are gone. only the symlinks are still there. 

- output of phive install is very verbose. Can we disable the progress bars of the downloads someway?

### CODE REVIEW

**Comment by theseer** [comment]
Let me know when this should get merged :)

**Comment by jaapio** [comment]
@theseer this one is ready for merge, unless you have a solution for the comments I have put in the pr :-)

**Comment by theseer** [comment]
I'll try to have a closer look at them, hopefully later today.

**Comment by theseer** [comment]
Okay, was simpler than I excepted ;)

>     * One problem I'm currently facing it the installation of tools by phive. The tools are symlinked in a docker container for that specific action. So after the action step is finished the tools are gone. only the symlinks are still there.

Use `--copy` ?


>     * output of phive install is very verbose. Can we disable the progress bars of the downloads someway?

`--no-progress` ?

**Comment by jaapio** [comment]
Ok, all set now. This one can be merged

**Comment by jaapio** [comment]
Thanks, for merging

**Pull request merged**
